### PR TITLE
update to 0.9.9

### PR DESCRIPTION
**Pull request by twrightsman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by twrightsman** [comment]
@conda-forge-admin, please rerender

**Comment by twrightsman** [comment]
I think this is blocked until https://github.com/marimo-team/marimo/pull/2651 makes it into the next release. Then this PR could be bumped to 0.9.11.

**Comment by mscolnick** [comment]
Sorry for the delay! @akshayka just releases 0.9.11

**Comment by twrightsman** [comment]
> Sorry for the delay!

@mscolnick All good! It's the weekend :smile:

**Pull request merged**
