### PR TITLE
marimo v0.6.0 and add maintainer

### PR DESCRIPTION
**Pull request by twrightsman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes https://github.com/conda-forge/marimo-feedstock/pull/70

### CODE REVIEW

**Comment by twrightsman** [comment]
@conda-forge-admin, please rerender

**Review by mfansler — APPROVED** [review]
Thanks @twrightsman!

Are you interested in joining as a maintainer here? It would let you touch up the autotick PRs rather than start new ones. If so, feel free to add your GitHub handle to the `recipe-maintainers` list.

**Comment by twrightsman** [comment]
I'm happy to help maintain the recipe if folks are okay with that; I added myself to the list

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Pull request merged**
