### PR TITLE
marimo v0.2.2

### PR DESCRIPTION
**Pull request by twrightsman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #26
Closes #27
Closes #28
Closes #29

### CODE REVIEW

**Comment by twrightsman** [comment]
@conda-forge-admin, please rerender

**Comment by twrightsman** [comment]
I'm not really sure if skipping PyPy is the appropriate action, but this is ready for review

**Review by mfansler — APPROVED** [review]
I think this is fine for now.

The PyPy builds fail to solve because [`uvloop` has failed to migrate](https://github.com/conda-forge/uvloop-feedstock/pull/44), and so `uvicorn` cannot migrate. It may have been cleaner to remove [the migration file](https://github.com/conda-forge/marimo-feedstock/blob/a7004440d4dae8d189fd385c0509081d6a899dcc/.ci_support/migrations/pypy38.yaml), rather than skip in the `meta.yaml`, but honestly, I think the artifacts will come out the same and this is probably easier to re-enable PyPy builds later.

**Comment by twrightsman** [comment]
@akshayka @mscolnick does this look okay to you? Would be awesome to test 0.2 through conda-forge

**Review by akshayka — APPROVED** [review]

**Comment by akshayka** [comment]
This looks good to me, thanks @twrightsman and @mfansler!

I was under the impression that `uvloop` was an optional dependency of `uvicorn` — but I guess it affects the solve nonetheless.

**Review by mfansler — APPROVED** [review]

**Pull request merged**
